### ISSUE TITLE
make setup for updating?

### ISSUE THREAD

**Issue by triska** [aarroyoc/doclog#1]
Currently, I get:

<pre>
<b>$ make setup</b>
git clone --depth 1 --branch v1.0.1 https://github.com/aarroyoc/teruel
fatal: destination path 'teruel' already exists and is not an empty directory.
</pre>

I wanted to run setup again to fetch the latest djota changes. How can I pull them? Thank you a lot!

**Comment by aarroyoc** [comment]
Now, `make setup` removes the previous folder if it exists
