### ISSUE TITLE
Backslashes sometimes missing

### ISSUE THREAD

**Issue by UWN** [aarroyoc/doclog#4]
https://github.com/mthom/scryer-prolog/issues/2228,
https://github.com/mthom/scryer-prolog/issues/2206

**Comment by aarroyoc** [comment]
This is expected. See https://htmlpreview.github.io/?https://github.com/jgm/djot/blob/master/doc/syntax.html (see Ordinary text section). The two options are doing a double backslash or just wrapping those occurrences in code blocks.

See https://github.com/mthom/scryer-prolog/pull/2229
